platform :ios, '9.0'
use_frameworks!

target 'NewReader' do

  pod 'SDWebImage', '~>3.8'
  # Pods for NewReader

  target 'NewReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
