platform :ios, '9.0'

target 'NewReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  pod 'SDWebImage', '~>3.8'
  # Pods for NewReader

  target 'NewReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
